ALTER TABLE dim_city 
ADD COLUMN IF NOT EXISTS latitude DECIMAL(9,6),
ADD COLUMN IF NOT EXISTS longitude DECIMAL(9,6);

ALTER TABLE fact_weather
ADD COLUMN IF NOT EXISTS wind_deg INTEGER,
ADD COLUMN IF NOT EXISTS pressure INTEGER,
ADD COLUMN IF NOT EXISTS visibility INTEGER;